export default ['Julio Iglesias',
'José Luis Rodriguez',
'Luis Miguel',
'Camilo Sesto',
'Emmanuel',
'Nino Bravo',
'Roberto Carlos',
'Ricardo Montaner',
'Raphael',
'José José',
'Christian Andrade',
'Axel (cantante)',
'Carlos Javier Beltrán',
'Manuela Bravo',
'Billy Cafaro',
'King Clave',
'Marty Cosens',
'Eddy Cramer',
'Fernando de Madariaga',
'Silvana Di Lorenzo',
'Donald',
'Alicia Duncan',
'Clever Dusseau',
'Carlos Alfredo Elías',
'Beto Fernán',
'Ricardo Fort',
'Joaquín Galán',
'Lucía Galán',
'Silvina Garré',
'Gladys, la Bomba Tucumana',
'Guillermo Guido',
'Ginamaría Hidalgo',
'Jairo',
'Juan Ramón',
'Leo Dan',
'Alejandro Lerner',
'Roberto Livi',
'Luciana',
'Andy Maciá',
'Cris Manzano',
'Luis Ángel Márquez',
'Paz Martínez',
'Laura Miller',
'Aldo Monges',
'Yaco Monti',
'Marco Montoya',
'Carlos Morell',
'Beto Orlando',
'Emanuel Ortega',
'Palito Ortega',
'Luciano Pereyra',
'Aldo Perricone',
'Pimpinela',
'Jorge Porcel',
'César "Banana" Pueyrredón',
'Raúl Padovani',
'Estela Raval',
'Daniel Riolobos',
'Antonio Ríos',
'Violeta Rivas',
'Elio Roca',
'Jorge Rojas',
'Hugo Romani',
'Pablo Ruiz',
'Raúl Sagán',
'Sandro',
'María Martha Serra Lima',
'Eddie Sierra',
'Patricia Sosa',
'Tormenta',
'Diego Torres',
'Twiggy',
'Bebo Veracruz',
'Vicentico',
'Julia Zenko',
]