export default ['Doug Anderson (singer)',
'Alan Bibey',
'Tyler Booth',
'Zac Brown',
'Preston Brust',
'Buford Abner',
'Larry Campbell (musician)',
'Fred Carter Jr.',
'Brian Collins (1970s singer)',
'Dudley Connell',
'Ken Curtis',
'Daughter of Swords',
'Tommy Dee',
'Donald DePoy',
'Guy Drake',
'Don Edwards',
'Karen Fairchild',
'Josh Herbert',
'Randy Howard (country singer)',
'Jerry Jaye',
'Hugh X. Lewis',
'Jim Lill',
'Chris Lucas (musician)',
'Dean Martin',
'Jennette McCurdy',
'Price Mitchell',
'Ryan Montgomery (singer)',
'Chuck Murphy (singer)',
'Jerry Naylor',
'Jay Osmond',
'Merrill Osmond',
'Charlie Phillips (singer)',
'Joe Poovey',
'Elvis Presley',
'Mason Ramsey',
'Steve Ripley',
'Weldon Rogers',
'Michael Sarver',
'Kimberly Schlapman',
'Earl Scott (singer)',
"Ramblin' Tommy Scott",
'Steven Seagal',
'Cal Smith',
'Carl Smith (musician)',
'Tommy Shane Steiner',
'Tate Stevens',
'Doug Supernaw',
'Philip Sweet',
'Taylor Swift',
'Ty Taylor (author)',
'B. J. Thomas',
'Kenneth Threadgill',
'Mitchell Torok',
'John Torres',
'Stephen Wesley',
'Jimi Westbrook',
]