export default ['Daniel Agostini',
'Alcides (cantante)',
'Miguel "Conejito" Alejandro',
'Angela Leiva',
'Verónica Ávila',
'Miss Bolivia (cantante)',
'Pedro Carreras',
'Adrián Chauque',
'Gustavo Cordera',
'Lía Crucet',
'Ezequiel "El Polaco" Cwirkaluk',
'Dolores De Cicco',
'Chili Fernández',
'Gilda (cantante)',
'Gladys, la Bomba Tucumana',
'Jackita',
'Karina (cantante argentina)',
'Karla (cantante)',
'Pocho La Pantera',
'Daniel Lescano',
'Pablo Lescano',
'Uriel Lozano',
'Ricky Maravilla',
'Mario Luis',
'Juan Carlos Mascheroni',
'Leo Mattioli',
'Román El Original',
'Pablo Ramón Ayala',
'Papichamp',
'El Pepo',
'Mario Pereyra',
'Eugenia Quevedo',
'Rocío Quiroz',
'Antonio Ríos',
'Ariel Salinas (músico)',
'Julio Silva (cantante)',
'Rodrigo Tapari',
'Maxi Tolosa',
'Lucas Velasco',
]