export default ['A-Trak',
'Above & Beyond',
'Marc Acardipane',
'Adrien Rux',
'Adventure Club',
'Lorenzo al Dino',
'Albert Neve',
'Alesso',
'Ellen Allien',
'Almunia (banda)',
'Alok',
'Alphazone',
'Rubén Amaya',
'Ananda Shake',
'Steve Angello',
'Angerfist',
'AN21',
'DJ Antoine',
'Steve Aoki',
'AronChupa',
'Arty',
'Astrix',
'ATB (DJ)',
'Juan Atkins',
'Dave Audé',
'Audioiko',
'Danny Ávila',
'Axwell',
'Axwell Λ Ingrosso',
'Marien Baker',
'Thomas Bangalter',
'Misstress Barbara',
'Bassjackers',
'Basto (DJ)',
'Blake Baxter',
'Chimo Bayo',
'Benny Benassi',
'Samantha Bentley',
'Ron van den Beuken',
'Franco Bianco',
'Big Chocolate',
'Bingo Players',
'Blank & Jones',
'Blasterjaxx',
'Leon Bolier',
'CJ Bolland',
'Gui Boratto',
'Borgeous',
'Borgore',
'Boys Noize',
'Breakbot',
'Aril Brikha',
'Bryan Brack',
'Bufi',
'Burns (DJ)',
'Junior Caldera',
'Michael Calfan',
'Mike Candys',
'Ian Carey',
'Carnage (DJ)',
'Marco Carola',
'Cash Cash',
'Liam Howlett',
'Hernán Cattáneo',
'Chab',
'Nic Chagall',
'Chuckie',
'Bart Claessen',
'Antoine Clamaran',
'Renato Cohen',
'Romina Cohn',
'Coone',
'Ferry Corsten',
'Arno Cost',
'Toni Costanzi',
'Carl Cox',
'Carl Craig',
'Culture Shock (DJ)',
'Cybotron',
`Gigi D'Agostino`,
'Dada Life',
`Daddy's Groove`,
'John Dahlbäck',
'Dannic',
'Danny Howells',
'Matt Darey',
'Dash Berlin',
'Datsik',
'JD Davis',
'Óscar de Rivera',
'Deep Dish',
'Tim Deluxe',
'Mac Demetrius',
'Deorro',
'Dero (DJ)',
'John Digweed',
'Angger Dimas',
'Dimitri from Paris',
'Dimitri Vangelis & Wyman',
'Dimitri Vegas & Like Mike',
'Dirty South (DJ)',
'Dirtyphonics',
'Disclosure (banda)',
'Sander van Doorn',
'Norman Doray',
'Dr. Kucho!',
'Dave Dresden',
'Dubfire',
'DubVision',
'Duke Dumont',
'DVBBS',
'Dyro',
'Erick E',
'Gareth Emery',
'Nora En Pure',
'Eptic',
'Dj Skudero',
'Xavi Metralla',
'Dominik Eulberg',
'Rasmus Faber',
'Fred Falke',
'Firebeatz',
'Pierre Fitch',
'DJ Flex',
'Flosstradamus',
'Fonzerelli',
'JOYRYDE',
'Eddie Fowlkes',
'Dillon Francis',
'Lupe Fuentes',
'Funkerman',
'Gabry Ponte',
'Josh Gabriel',
'Galantis (banda)',
'Joachim Garraud',
'Martin Garrix',
'Wolfgang Gartner',
'Alex Gaudino',
'Geamclo',
'A Guy Called Gerald',
'Cedric Gervais',
'Johan Gielen',
'Benno de Goeij',
'Thomas Gold (DJ)',
'DJ Valdi',
'Gouryella',
'Fedde le Grand',
'Francis Grasso',
'GTA (banda)',
'David Guetta',
'Seamus Haji',
'Lindstrøm (músico)',
'Hard Rock Sofa',
'Jay Hardway',
'Ron Hardy',
'Calvin Harris',
'Richie Hawtin',
'Oliver Heldens',
'DJ Hell',
'Mary Anne Hobbs',
'Guy-Manuel de Homem-Christo',
'Hot Since 82',
'Felix da Housecat',
'Mike Huckaby',
'Sebastian Ingrosso',
'Ken Ishii',
'Junior Jack',
'Jam Aunni',
'James Pennington',
'Deadmau5',
'Jax Jones',
'Menno de Jong',
'Julian Jordan',
'Jorn van Deynhoven',
'Judge Jules',
'Jump Smokers',
'Junkie XL',
'DJ Jurgen',
'Justice (banda)',
'Fritz Kalkbrenner',
'Paul Kalkbrenner',
'Kamaya Painters',
'Daniel Kandi',
'Kaskade',
'Kemistry & Storm',
'Kenny Larkin',
'François Kevorkian',
'Kirk Degiorgio',
'Klaas',
'Sander Kleinenberg',
'Mark Knight',
'Otto Knows',
'Frankie Knuckles',
'Kostrok',
'Deniz Koyu',
'Monika Kruse',
'Kyau & Albert',
'Kygo',
'Lady Starlight',
'Chris Lake',
]