export default ['°C-ute',
'10,000 Promises.',
'175R',
'19',
'2BACKKA',
'3B LAB.☆',
'7 HOUSE',
'9nine',
'Aa!',
'AAA',
'Abe, Mao',
'Abe, Natsumi',
'Abe, Yasuhiro',
'Abe, Yoshiharu',
'Access',
'Acid Black Cherry',
'Aco',
'Ai',
'Aiba, Masaki',
'Aida, Shoko',
'Aikawa, Hiroki',
'Aikawa, Nanase',
'Aiko',
'Aimer',
'Aimyon',
'Air',
'Aira, Mitsuki',
'Aiso, Haruhi',
'Aiuchi, Rina',
'Ajico',
'Akanishi, Jin',
'Akashi, Momoka',
'AKB48',
'Akeboshi',
'Akishibu Project',
'Aki, Angela',
'Akiyama, Satoko',
'Alan',
'The Alfee',
'Ali Project',
'Alma Kaminiito',
'Ami Suzuki',
'Amiaya',
'Amuro, Namie',
'Anai, Yuko',
'Angela',
'Angerme',
'Anly',
'Anna S',
'Anzenchitai',
'Aonishi, Takashi',
'Aoyama, Thelma',
'Aqua Timez',
'Aragaki, Yui',
'Arashi',
'Arashiro, Beni',
'Arioka, Daiki',
'Asakura, Daisuke',
'Asaoka, Megumi',
'Asian Kung-Fu Generation',
'Ayabie',
'Ayaka',
'Ayana',
'AZU',
"B'z",
'Babamania',
'BaBe',
'Babymetal',
'Back-On',
'Bakusute Sotokanda Icchome',
'Base Ball Bear',
'BeForU',
'Bennie K',
'Berryz Koubou',
'Beyooooonds',
'Bis',
'Bish',
'Bluem of Youth',
'Bon-Bon Blanco',
'Bonnie Pink',
'Breath',
'Bright',
'The Brilliant Green',
'Bullet Train',
'bump.y',
'Bump of Chicken',
'Buono!',
'Buzy',
'Candies',
'Capsule',
'Carry Loose',
'CHAGE and ASKA',
"Changin' My Life",
'Chara',
'Charcoal Filter',
'Chatmonchy',
'Chemistry',
"Che'Nelle",
'Cheeky Parade',
'Chiba, Saeko',
'Chihara, Minori',
'Chinen, Rina',
'Chinen, Yuri',
'ClariS',
"Clear's",
'Coconuts Musume',
'College Cosmos',
'Cool Joke',
'CooRie',
'Core of Soul',
'Country Musume',
'Crystal Kay',
'CY8ER',
'CYNHN',
'D-51',
'D&D',
'D DATE',
'Da-iCE',
'Da Pump',
'DAOKO',
'Danceroid',
'Dancing Dolls',
'Day After Tomorrow',
'Deen',
'Dempagumi.inc',
'DEPAPEPE',
'Dicot',
'Dish',
'Diva',
'Dizon, Leah',
'DJ Ozma',
'Do As Infinity',
'Dohzi-T',
'Dōmoto, Kōichi',
'Dōmoto, Tsuyoshi',
'Dream',
'Dream Morning Musume',
'Dreams Come True',
'DRM',
'E-girls',
'E.mu',
'Earth',
'Ebichu',
'Elisa',
'Empire',
'Emyli',
'Eto, Rie',
'Etsuko Yakushimaru',
'Eu Phoria',
'Every Little Thing',
'EXILE',
'Fairies',
'Faky',
'Favorite Blue',
'Faylan',
'Fayray',
'FictionJunction Yuuka',
'Field of View',
"Flap Girls' School",
"Flipper's Guitar",
'FLOW',
'flumpool',
'Folder 5',
'Four Leaves',
'French Kiss',
'fripSide',
'Fu, Rie',
'Fujii, Fumiya',
'Fukada, Kyoko',
'Fukuda, Saki',
'Fukusaki, Eric',
'Fukuyama, Masaharu',
'Funky Monkey Babys',
'Furukawa, Yūta',
'Gackt',
'Gang Parade',
'Garnet Crow',
'Generations from Exile Tribe',
'Girl Next Door',
'Glay',
'Globe',
"Go-Bang's",
'Gold, Taro',
'Golden Bomber',
'Goto, Maki',
'Go To The Beds',
'GReeeeN',
'Guardians 4',
'H-wonder',
'Hajime, Chitose',
'Hal',
'HALCALI',
'Hamada, Mari',
'Hamasaki, Ayumi',
'Hanazawa, Kana',
'hANGRY&ANGRY',
'Harada, Shinji',
'Haruna, Luna',
'Hata, Motohiro',
'Hatsune Miku',
'Hayashi, Asuca',
'Hayashi, Nobutoshi',
'Hayashibara, Megumi',
'Hearts Grow',
'Heartsdales',
'Hey! Say! JUMP',
'High-King',
'Hikashu',
'Himeka',
'Hinoi, Asuka',
'Hinoi Team',
'Hinouchi, Emi',
'Hirahara, Ayaka',
'Hirai, Ken',
'Hirano, Aya',
'Hirose, Kōmi',
'Hisakawa, Aya',
'Hitomi',
'Hitoto, Yō',
'HKT48',
'Hōkago Princess',
'Home Made Kazoku',
'Honda, Minako',
'Horie, Mitsuko',
'Horie, Yui',
'Hoshimura, Mai',
'Hotch Potchi',
'HY',
'Hysteric Blue',
'I WiSH',
'Ice Creamusume',
'Iceman',
'Ichii, Sayaka',
'Idol College',
'Idol Renaissance',
'Idoling!!!',
'Iijima, Mari',
'Iizuka, Mayumi',
'Ikeda, Ayako',
'Ikimonogakari',
'Imai, Miki',
'Inaba, Koshi',
'The Indigo',
'Inoo, Kei',
'Inoue, Kazuhiko',
'Inoue, Kikuko',
'Irino, Miyu',
'Ishida, Yoko',
'Ishii, Tatsuya',
'Ishikawa, Chiaki',
'Ishikawa, Rika',
'Isoya, Yuki',
'Itano, Tomomi',
'Itō, Yuna',
'Iwata, Sayuri',
'i☆Ris',
'J Soul Brothers',
'JAM Project',
'Janne Da Arc',
'Jasmine',
"Jay'ed",
'Jero',
'JO1',
'Judy and Mary',
'Juice=Juice',
'JUJU',
'June',
'Jungle Smile',
'Jyongri',
'Jyukai',
'K',
'Kageyama, Hironobu',
'Kahala, Tomomi',
'Kahimi Karie',
'kalafina',
'Kaji, Meiko',
'Kamiki, Aya',
'Kanjani Eight',
'Kanno, Yoko',
'KAT-TUN',
'Katakiri, Rekka',
'Kato, Miliyah',
'Kawabe, Chieko',
'Kawada, Mami',
'Kawase, Tomoko',
'Kawashima, Ai',
'Kawasumi, Ayako',
'Kayo, Aiko',
'Ketsumeishi',
'Keyakizaka46',
'Kick the Can Crew',
'Kids Alive',
'Kikkawa, Kōji',
'Kimeru',
'Kimura, Kaela',
'King Gnu',
'KinKi Kids',
'Kotani, Kinya',
'Kirinji',
'Kiroro',
'Kis-my-ft2',
'Kishimoto, Hayami',
'Kitade, Nana',
'Kiyokiba Shunsuke',
'Kobukuro',
'Kōda, Kumi',
'Kōda, Mariko',
'Kokia',
'Kolme',
'Komatsu, Miho',
'Kome Kome Club',
'Kosaka, Riyu',
'KOTOKO',
'Koyanagi, Yuki',
'Kudo, Shizuka',
'Kumaki, Anri',
'Kuraki, Mai',
'Kuroki, Meisa',
'Kushida, Akira',
'Kusumi, Koharu',
'Kuwata, Keisuke',
'Kyary Pamyu Pamyu',
"L'Arc~en~Ciel",
"L'luvia",
'Ladybaby',
'Lead',
'Lia',
'Lindberg',
'LiSA (Japanese musician, born 1987)',
'Little by Little',
'Little Glee Monster',
'LM.C',
'Love',
'Love Psychedelico',
'Lufkin, Olivia',
'M-Flo',
'Maeda, Ai',
'Maeda, Atsuko',
'Maeda, Yuki',
'Magnolia Factory',
'Mai',
'Maison book girl',
'Makihara, Noriyuki',
'Makino, Yui',
'Mameshiba no Taigun',
'Mano, Erina',
'marble',
'Masuda, Keiko',
'Masuda, Yuri',
'Matsu, Takako',
'Matsuda, Seiko',
'Matsui Jurina',
'Matsui Rena',
'Matsumoto, Jun',
'Matsushita, Yuya',
'Matsutoya, Yumi',
'Matsuura, Aya',
'Mawatari, Matsuko',
'MAX',
'May J.',
"May'n",
'Mell',
'Mellow Mellow',
'Melocure',
'melody.',
'Melon Kinenbi',
'Metis',
'MiChi',
'Mie',
'mihimaru GT',
'MilkyWay',
'Minawo',
'Minekawa, Takako',
'Mini Moni',
'Mink',
'Minmi',
'MIQ',
'Misato, Aki',
'Misia',
'misono',
'Miura, Daichi',
'Miyano, Mamoru',
'Miyavi',
'Miyazaki, Ayumi',
'Shinji Miyazaki',
'Miz',
'Mizca',
'Mizuki, Nana',
'Momoi, Haruko',
'MONGOL800',
'MONKEY MAJIK',
'Moriguchi, Hiroko',
'Morikawa, Miho',
'Moritaka, Chisato',
'Moriyama, Naotarō',
'Momoiro Clover Z',
'Morning Musume',
'Motohiro Hata',
'moumoon',
'm.o.v.e',
'Mr.Children',
'Myco',
'My Little Lover',
'Nakagawa, Shōko',
'Nakahara, Mai',
'Nakajima, Miyuki',
'Nakajima, Yuto',
'Nakamori, Akina',
'Nakanishi, Toshio',
'Nakashima, Mika',
'Nakayama, Miho',
'Nakayama, Uri',
'Nakayama, Yuma',
'Natsukawa, Rimi',
'Nemuri, Haru',
'NEWS',
'Ninomiya, Kazunari',
'Nishikawa, Takanori',
'Nishino, Kana',
'NiziU',
'NGT48',
'NMB48',
'no3b',
'Nobodyknows+',
'Nogizaka46',
'Nomiya, Maki',
'Not yet',
'NYC',
'N Zero',
'Oda, Kazumasa',
'Odani, Misako',
'Official Hige Dandism',
'Ogata, Megumi',
'Ogura, Kei',
'Ohguro, Maki',
'Ohno, Satoshi',
'Okada, Yukiko',
'Okamoto, Keito',
'Okazaki, Ritsuko',
'Okuda, Tamio',
'Okui, Masami',
'Onitsuka, Chihiro',
'Ono, Erena',
'Ono, Lisa',
'On/Off',
'OnePixcel',
'Orange Pekoe',
'ORANGE RANGE',
'Oshima, Hanako',
'Oshima, Yuko',
'Oshio, Kotaro',
'Otsuka, Ai',
'Ozaki, Ami',
'Ozaki, Yutaka',
'Ozawa, Kenji',
'Paradises',
'Paris match',
'Passpo',
'Perfume',
'Piggs',
'Piko',
'PINK CRES.',
'Pink Lady',
'Pistol Valve',
'Pizzicato Five',
'Plastics',
'Porno Graffitti',
'The Possible',
'Princess Princess',
'PrizmaX',
'Prizmmy☆',
'Psychic Lover',
'PUFFY',
'Quruli',
'Rag Fair',
'Rake',
'Rats & Star',
'Ray',
'Remioromen',
'Rinoie, Joe',
'Rip Slyme',
'RIRI',
'Romantic Mode',
'Round Table',
'Royz',
'Run&Gun',
'Rurutia',
'Rythem',
'Ryutist',
'S/mileage',
'Sada, Masashi',
'Saiga, Mitsuki',
'Saijo, Hideki',
'Saito, Yuki',
'Sakai, Mikio',
'Sakai, Noriko',
'Sakakibara, Yui',
'Sakamoto, Kyu',
'Sakamoto, Maaya',
'Sakamoto, Miu',
'Sakamoto, Ryuichi',
'Sakura Gakuin',
'Sakurai, Sho',
'Sakurai, Tomo',
'Salyu',
'Sandii & the Sunsetz',
'Sano, Motoharu',
'Saori@destiny',
'Sashihara, Rino',
'Satō, Hiromi',
'savage genius',
'Sayaka Maizono[5]',
'Sayuri',
'Sid',
'SAWA',
'Sawada, Kenji',
'Erika Sawajiri',
'SCANDAL',
'The Scanty',
'School Food Punishment',
'SDN48',
'Seagull Screaming Kiss Her Kiss Her',
'See-Saw',
'Sekai no Owari',
'Sexy Zone',
'Sharam Q',
'Shibasaki, Kou',
'Shibata, Jun',
'Shiina, Ringo',
'Shimabukuro, Hiroko',
'Shimamiya, Eiko',
'Shimatani, Hitomi',
'Shimizu, Ai',
'Shota Shimizu',
'Shimokawa, Mikuni',
'Shinohara, Tomoe',
'Shintani Ryōko',
'Shiritsu Ebisu Chugaku',
'Shirota, Yū',
'Shishido, Rumi',
'Shugo Chara Egg!',
'Sifow',
'Silent Siren',
'SKE48',
'SMAP',
'Snow',
'Sonim',
'Sophia',
'Sora tob sakana',
'Southern All Stars',
'Sowelu',
'SPEED',
'Spitz',
'Stereopony',
'Suga, Shikao',
'Straightener',
'Sukima Switch',
'Sunmyu',
'Sunny Day Service',
'SunSet Swish',
'Super Girls',
`Super Monkey's`,
'Supercar',
'supercell',
'Superfly',
'Suzuki, Airi',
'Suzuki, Ami',
'Suzuki, Masayuki',
'Suzumura, Kenichi',
'SweetS',
'T-Bolan',
'Tackey and Tsubasa',
'Tadokoro, Azusa',
'Tainaka, Sachi',
'Takahashi, Hitomi',
'Takahashi, Minami',
'Takahashi, Naozumi',
'Takahashi, Yoko',
'Takaki, Yuya',
'Tamaki, Nami',
'Tamura, Eriko',
'Tamura, Yukari',
'Tamurapan',
'Tanimura Nana',
'Tanaka, Rie',
'Tange, Sakura',
'Tanpopo',
'Team Syachihoko',
'Tegomass',
'Teriyaki Boyz',
'Terra',
'Teshima, Aoi',
'Tetsuya',
'TiA',
'tiaraway',
'The World Standard',
'TM Network',
'T.M.Revolution',
'Togawa, Jun',
'東方神起',
'Tokio (band)',
'Tokumaru, Shugo',
`Tokyo Girls' Style`,
'Tokyo Jihen',
'TRF',
'TrySail',
'Tsuchiya, Anna',
'Tsuchiya, Masami',
'Tsunku',
'Tsuyuzaki, Harumi (Lyrico)',
'Tube (band)',
'TWICE',
'Twinklestars',
'Two-Mix',
'U-ka saegusa IN db',
'UA',
'Uchida, Maaya',
'Uchida, Yuki',
'Uehara, Azumi',
'Uehara, Takako',
'Uijin',
'Ulfuls',
'Utada, Hikaru',
'Utatsuki, Kaori',
'Utoku, Keiko',
'Uverworld',
'v-u-den',
'V6',
'Valshe',
'Van, Tomiko',
'ViViD',
'W',
'w-inds.',
'Wada, Kōji',
'Wagakki Band',
'WANDS',
'WaT',
'Watanabe, Mayu',
'Watanabe, Misato',
'Watarirouka Hashiritai',
'Weather Girls',
'White Ash',
'Whiteberry',
'WHY@DOLL',
'Wink',
'Wino',
'Wyse',
'Ya-ya-yah',
'Yabu, Kota',
'Yaida, Hitomi',
'Yamada, Keiko',
'Yamada, Ryosuke',
'Yamaguchi, Momoe',
'Yamashita, Tatsuro',
'Yamashita, Tomohisa',
'Yamazaki, Masayoshi',
'Yanagi, Nagi',
'Yano, Maki',
'Yaotome, Hikaru',
'Yazumi, Kana',
'Yellow Generation',
'Yoji Biomehanika',
'Yonekura, Chihiro',
'Kenshi Yonezu',
'Yorico',
'Yōsei Teikoku',
'Yoshida, Miwa',
'Yoshida, Takuro',
`You'll Melt More!`,
'Younha',
'YUI',
'YUKA',
'Yukana',
'Yuki',
'Yuko Anai',
'Yuma Nakayama w/B.I.Shadow',
'Yumemiru Adolescence',
'Yuna Ito',
'YURIA',
'Yusa, Mimori',
'Yuzu',
'Yumi Shizukusa',
'ZARD',
'Zebra Queen',
'Zenbu Kimi no Sei da.',
'Zone',
'Zoo',
'ZYX',
'ZZ',
]