export default ['Accept',
'Armageddon Holocaust',
'Bad4Good',
'Barren Cross',
'Black Label Society',
'Cathedral',
'Chastain',
'Circle II Circle',
'Circus of Power',
'Coven (banda)',
'Damnocracy',
'DeathRiders',
'Delirium (banda)',
'Deliverance (banda)',
'Factor VIII (banda)',
'Frameshift',
'GZR',
'Liege Lord',
'Magdallan',
'Mercyful Fate',
'Myrath',
'N17',
'Outface',
'Overdose (banda)',
'Pentagram (banda estadounidense)',
'Quiet Riot',
'Sinner (banda)',
'Skid Row',
'Steel Dragon',
'Steel Prophet',
'Taking Dawn',
'TT Quick',
'V8 (banda)',
'Vicious Rumors',
'Voodoocult',
'W.A.S.P.',
]