export default ['1 Girl Nation',
'13 Stories',
'2 Unlimited',
'3OH!3',
'Paula Abdul',
'Ace of Base',
'Christina Aguilera',
'Alcazar',
'AlunaGeorge',
'A-L-X',
'Ambitious Lovers',
'Anastacia',
'Annie',
'Aqua',
'David Archuleta',
'Tina Arena',
'Army of Lovers',
'Rick Astley',
'Atomic Kitten',
'The Attic',
'Audio Playground',
'Aurora',
'Avicii',
'Axé Bahia',
'B*Witched',
'Backstreet Boys',
'Bad Boys Blue',
'Zoë Badwi',
'Bananarama',
'Banghra',
'Azealia Banks',
'Bardeux',
'Basement Jaxx',
'Bastille',
'Daniel Bedingfield',
'The Beloved',
'Betty Who',
'The Beu Sisters',
'Beyoncé',
'Justin Bieber',
'The Black Eyed Peas',
'Black Kids',
'Blood Orange',
'Bloodshy & Avant',
'The Boomtang Boys',
'La Bouche',
'David Bowie',
'Brazilian Girls',
'Bronski Beat',
'Chris Brown',
'Havana Brown',
'Emma Bunton',
'C+C Music Factory',
'Can-linn',
'Mariah Carey',
'Caribou',
'Dina Carroll',
'Aaron Carter',
'Cascada',
'Cause and Effect',
'Charli XCX',
'Cher',
'Neneh Cherry',
'China Doll',
'Ciara',
'Classixx',
'Clean Bandit',
'Cobra Starship',
'Kimberly Cole',
'The Communards',
'Company B',
'Ida Corr',
'The Cover Girls',
'Taio Cruz',
'Cut Copy',
'Da Pump',
'Taylor Dayne',
'DB Boulevard',
'Dead Disco',
'Dead or Alive',
'Dee Dee',
'Deee-Lite',
'Delorean',
'Kat DeLuna',
`Destiny's Child`,
'Deuce',
'Dev',
'DHT',
'Celine Dion',
'Disclosure',
'DJ BoBo',
'DJ Encore',
'Dubstar',
'Hilary Duff',
'Stacy Earl',
'East 17',
'Eiffel 65',
'Sophie Ellis-Bextor',
'Empire of the Sun',
'Jocelyn Enriquez',
'Gloria Estefan',
'Everything Everything',
'Exposé',
'Sky Ferreira',
'Fifth Harmony',
'Five',
'Flo Rida',
'Foster the People',
'Samantha Fox',
'Frankie Goes to Hollywood',
'Fun Factory',
'Debbie Gibson',
'Girls Aloud',
'globe',
'The Go! Team',
'Selena Gomez',
'Wynter Gordon',
'Gorillaz',
'Ellie Goulding',
'Ariana Grande',
'David Guetta',
'Her Majesty & the Wolves',
'Paris Hilton',
'Hurts',
'Innosense',
'La Toya Jackson',
'Janet Jackson',
'Michael Jackson',
'Samantha James',
'Jewel',
'Joée',
'Joy',
'Jump5',
'Junior Senior',
'Juvelen',
'Kesha',
'Mary Kiani',
'Natalia Kills',
'Kim Hyun-jung',
'King África',
'Kisses',
'The KLF',
'Solange Knowles',
'Lady Gaga',
'Laila',
'George Lamond',
'Jessy Lanza',
'LCD Soundsystem',
'Lisa Lisa and Cult Jam',
'LMFAO',
'Locomía',
'Jennifer Lopez',
'Louie Louie',
'Luciana',
'M People',
'Madonna',
'Maroon 5',
'Lisa Matassa (as Lysa Lynn)',
'Matt and Kim',
'Mel and Kim',
'Javiera Mena',
'M.I.A.',
'Miami Sound Machine',
'George Michael',
'MiChi',
'Mika',
'Milli Vanilli',
'Nicki Minaj',
'Dannii Minogue',
'Kylie Minogue',
'Modern Talking',
'Moloko',
'Momoiro Clover Z',
'Alanis Morissette',
'm.o.v.e',
'Movetron',
'Samantha Mumba',
'James Murphy',
'Róisín Murphy',
'N-Trance',
'Nabiha',
'The Neptunes',
'New Kids on the Block',
'Olivia Newton-John',
'Ne-Yo',
'Nikkole',
'NRG',
'NSYNC',
'OFF',
'Emily Osment',
'Donny Osmond',
'Kevin Paige',
'Paradiso Girls',
'Sarina Paris',
'Pebbles',
'Katy Perry',
'Paul Pesco',
'Pet Shop Boys',
'Pink',
'Pizzicato Five',
'Play',
'Pnau',
'Gabry Ponte',
'Prima J',
'Prince',
'Private',
'The Pussycat Dolls',
'Cara Quici',
'Raze',
'Richard X',
'Ricki-Lee',
'Right Said Fred',
'Rihanna',
'Robyn',
'Rockell',
'Kelly Rowland',
'S Club 7',
'Marta Sánchez',
'Santigold',
'The Saturdays',
'Seiko Matsuda',
'Selena Gomez & the Scene',
'September',
'Shakira',
'Shinee',
'Shura',
'Sia',
'Jessica Simpson',
'Troye Sivan',
'Sam Smith',
'Solid HarmoniE',
'Tommy Sparks',
'Britney Spears',
'Speed',
'Spice Girls',
'Stacey Q',
'Stakka Bo',
'Alexandra Stan',
'Lisa Stansfield',
'Brenda K. Starr',
'Gwen Stefani',
'Steps',
'Stevie B',
'Stock Aitken Waterman',
'Sugababes',
'Linda Sundblad',
'Swedish House Mafia',
'Taylor Swift',
'Sylvan Esso',
'T-ara',
'T-Spoon',
'Take That',
'Tarkan',
't.A.T.u.',
'Tegan and Sara',
'Therese',
'Tiësto',
'Tiffany',
'Timbaland',
'Justin Timberlake',
'The Ting Tings',
'Katy Tiz',
'Melissa Tkautz',
'TLC',
'Judy Torres',
'Totally Enormous Extinct Dinosaurs',
'Jolin Tsai',
'Usher',
'Vassy',
'Vengaboys',
'V*Enna',
'The Very Best',
'Vitamin C',
'Wallpaper',
'Jessie Ware',
'Pete Waterman',
'Jody Watley',
'Wham!',
'Karyn White',
'Wild Orchid',
'Will to Power',
'Vanessa L. Williams',
'Kimberly Wyatt',
'XLR8',
'Xuxa',
'Yazz',
'Yelle',
'Yuri',
'ZOEgirl',
]