export default ['+44',
'22 Jacks',
'5 Seconds of Summer',
'999',
'A Day to Remember',
'The Academy Is...',
'Ace Troubleshooter',
'Acceptance',
'AFI',
'Against the Current',
'Alien Ant Farm',
'Alkaline Trio',
'A Loss for Words',
'All',
'The All-American Rejects',
'All Time Low',
'Allister',
'Amber Pacific',
'American Hi-Fi',
'Army of Freshmen',
'Anarbor',
'As It Is',
'Ash',
'The Ataris',
'The Audition',
'Audio Karate',
'Autopilot Off',
'Avril Lavigne',
'Beat Crusaders',
'Better Luck Next Time',
'Big Drill Car',
'Billy Talent',
'Blink-182',
'Bodyjar',
'Boris the Sprinkler',
'The Bouncing Souls',
'Bowling for Soup',
'Box Car Racer',
'The Boys',
'Boys Like Girls',
'Bracket',
'Brand New',
'Broadside',
'Busted',
'Buzzcocks',
'The Cab',
'Carousel Kings',
'Cartel',
'Cayetana',
'Charli XCX',
'Chasing Morgan',
'Chixdiggit',
'Chunk! No, Captain Chunk!',
'The Click Five',
'The Copyrights',
'Count the Stars',
'Courage My Love',
'Crash Romeo',
'Crimpshrine',
'Cub',
'Cute Is What We Aim For',
'Daggermouth',
'The Dangerous Summer',
'David Crowder Band',
'The Dead Milkmen',
'Descendents',
'The Donnas',
'The Downtown Fiction',
'Driving East',
'Dum Dums',
'Eat Me Raw',
'Every Avenue',
'Eleventyseven',
'Elliot Minor',
'Energy',
'The Ergs!',
'Eternal Boy',
'Eve 6',
'Even in Blackouts',
'Everyday Sunday',
'Faber Drive',
'Face to Face',
'Falling in Reverse',
'Fall Out Boy',
'Farewell',
'Fenix TX',
'Fight Fair',
'Finley',
'Fireworks',
'Flatfoot 56',
'Flop',
'fluf',
'FM Static',
'Fonzie',
'Forever Came Calling',
'Forever The Sickest Kids',
'Four Year Strong',
'The Friday Night Boys',
'Generation X',
'The Get Up Kids',
'Ghoti Hook',
'Go Betty Go',
'Go Radio',
'Gob',
'Goldfinger',
'Good Charlotte',
'Goodnight Nurse',
'Green Day',
'Greyfield',
'Groovie Ghoulies',
'Guttermouth',
'Hagfish',
'Halifax',
'Handguns',
'Hangnail',
'Hawk Nelson',
'Head Injuries',
'Hedley',
'Hey Monday',
'Hey Violet',
'Hidden in Plain View',
'The Hi-Fives',
'The High Court',
'The Higher',
'The Hippos',
'Hit the Lights',
'Home Grown',
'House of Heroes',
'Houston Calls',
'The Huntingtons',
'I Call Fives',
'Icon for Hire',
'Ivoryline',
'The Jam',
'Jawbreaker',
'Jimmy Eat World',
'June',
'Just Surrender',
'Kid Down',
'Kids in Glass Houses',
'Kids in the Way',
'Killerpilze',
'Kiros',
'Kisschasy',
'Knuckle Puck',
'Koopa',
'Latterman',
'Left Front Tire',
'The Leftovers',
'The Lemonheads',
'Less Than Jake',
'Lifesavors',
'Lifetime',
'Light Years',
'Like Pacific',
'The Lillingtons',
'Limbeck',
'Lit',
'Lola Ray',
'Love You to Death',
'Lucky 7',
'Lucky Boys Confusion',
'Ludo',
'Lustra',
'Machine Gun Kelly',
'Mach Pelican',
'Magnapop',
'The Maine',
'Makeout',
'Man Overboard',
'Manges',
'Marianas Trench',
'The Matches',
'Mayday Parade',
'McBusted',
'McFly',
'Me First and the Gimme Gimmes',
'Melody Fall',
'Mest',
'The Methadones',
'Midtown',
'Millencolin',
'Mixtapes',
'Moose Blood',
'Momoiro Clover Z',
'Motion City Soundtrack',
'Modern Baseball',
'The Movielife',
'The Mr. T Experience',
'The Muffs',
'MxPx',
'My Chemical Romance',
'Neck Deep',
'Nerf Herder',
'The New Cities',
'New Found Glory',
'New Years Day',
'NOFX',
'Noise By Numbers',
'Not By Choice',
'No Use for a Name',
'October Fall',
'The Offspring',
'On My Honor',
'One Ok Rock',
'Orange',
'Over It',
'Paige',
'Parasites',
'Paramore',
'Pardon Us',
'Panic! at the Disco',
'Patent Pending',
'Permanent Me',
'Pee Wee Gaskins',
'Philmont',
'Pierce the Veil',
"Plain White T's",
'Plinko',
'Pointed Sticks',
'Poor Old Lu',
'The Presidents of the United States of America',
'Propagandhi',
'Punchbuggy',
'Punchline',
'PUP',
'The Queers',
'Quietdrive',
'Rancid',
'Real Friends',
'Red City Radio',
'The Red Jumpsuit Apparatus',
'Reggie and the Full Effect',
'Relient K',
"Riddlin' Kids",
'Roam',
'Rookie of the Year',
'Rudi',
'Rufio',
'Run Kid Run',
'Saves the Day',
'Say Anything',
'Saving Aimee',
'Scenes from a Movie',
'Scott Murphy',
'Screeching Weasel',
'Seaway',
'Senses Fail',
'Set It Off',
'Set Your Goals',
'Shook Ones',
'Short Stack',
'Showoff',
'Simple Plan',
'Sleeping with Sirens',
'Sleep On It',
'Slick Shoes',
'Sludgeworth',
'Smash Mouth',
'Smoking Popes',
'Something Corporate',
'Son of Dork',
'The Soviettes',
'Spanish Love Songs',
'Sparks the Rescue',
'Spazzys',
'Split Habit',
'SR-71',
'Stand Atlantic',
'The Starting Line',
'State Champs',
'Stellar Kart',
'Stereos',
'Steriogram',
'Stiff Dylans',
'Story of the Year',
'The Story So Far',
'Student Rick',
'Sum 41',
'Supergrass',
'Superman Is Dead',
'The Summer Obsession',
'The Summer Set',
'Sweet Baby',
'The Swellers',
'Tacocat',
'Taking Back Sunday',
'Teen Idols',
'Teenage Bottlerocket',
'Ten Second Epic',
'Terrible Things',
'There for Tomorrow',
'These Kids Wear Crowns',
'This Century',
'This Time Next Year',
'Tigers Jaw',
'Tilt',
'Title Fight',
'Tonight Alive',
'Transit',
'Trash Boat',
'The Travoltas',
'Treble Charger',
'Trucks',
'Twenty Twenty',
'Undercover',
'The Undertones',
'The Unlovables',
'Unwritten Law',
'Valencia',
'The Vandals',
'Vanilla Sky',
'Verona Grove',
'Violent Delight',
'W',
'Waterparks',
'Wavves',
'Wakefield',
'We Are the in Crowd',
'The Wedding',
'Weezer',
'We the Kings',
'Wheatus',
'With Confidence',
'The Wonder Years',
'WSTR',
'Yellowcard',
'You Me at Six',
'Zebrahead',
'Zolof the Rock and Roll Destroyer',
]