export default ['The Alchemist (musician)',
'Lloyd Banks',
'Big Noyd',
'Boyfriend (musician)',
'D-Lo',
'Dark Denim',
'Darkim Be Allah',
'Dave Dave',
'DB Tha General',
'Deezle',
'Dem Atlas',
'Den Fenn',
'Blacka Di Danca',
'Digital Nas',
'Divine Council (group)',
'DJ Luke Nasty',
'Doe Boy (rapper)',
'Dolla Will',
'Jasper Dolphin',
'Don Q (rapper)',
'Donald D',
'Tiny Doo',
'Doonie Baby',
'Down Low Recka',
'Du-Lilz',
'Dubb 20',
'Duna (rapper)',
'Egyptian Lover',
'Evidence (musician)',
'Kari Faux',
'Flakiss',
'Stan Fortuna',
'Free Murda',
'Chaz French',
'G-Note',
'G-Nut',
'G-Stack',
'G.P. Wu',
'Trigga tha Gambler',
'The Game (rapper)',
'Gashi (rapper)',
'O.T. Genasis',
'Domo Genesis',
'Gizzle',
'Stephen Glover (screenwriter)',
'Gold Chains',
'Norman D. Golden II',
'GQ (actor)',
'Niem Green',
'Elisakh Hagia',
'Arin Hanson',
'Hefe Heetroc',
'Kalyn Heffernan',
'Chef Henny',
'Hodgy',
'Humpty Hump',
'Hush (rapper)',
'IRAWniQ',
'IshDARR',
'Jason Ivy',
'Mikey Jarrett, Jr.',
'Jay Biz',
'Joe Mafia',
'Young Joshua',
'Julian B',
'June Luva',
'Larry June',
'Justus (musician)',
'K Camp',
'K-Rob',
'Kaveo',
'KayO Redd',
'Kaz Kyzah',
'Max Kellerman',
'Key Glock',
'Kidd Kidd',
'Killa Keise',
'King Just',
'Kodak Black',
'Kodie Shane',
'Howard Kremer',
'Krondon',
'Kryme Life',
'Mike Ladd',
'LehtMoJoe',
'Lil Baby',
'Lil Coner',
'Lil iROCC Williams',
'Lil JSean',
'Lil Mosey',
'Lil Uno',
"Lil' C-Style",
"Lil' Fame",
'Liquid (rapper)',
'Lord Superb',
'Lounge Lo',
'Lushlife',
'Ace Mack',
'Madd Maxx',
'Lee Majors (rapper)',
'Mapei (musician)',
'Master Gee (musician)',
'Dan Maynes-Aminzade',
'Kevin McCall',
'Me Phi Me',
'Miami (rapper)',
'Chris Miles (musician)',
'Karlous Miller',
'Janelle Monáe',
'Murda Mook',
'Jeff Moonie Jr.',
'Markice Moore',
'Mark Moseley (actor)',
'Mr. Malik',
'Mr. Skrillz',
'Mr. SOS',
'Mugzi',
'Kaila Mullady',
'Remy Munasifi',
'Myalansky',
'Nasty Nigel (rapper)',
'River Nelson',
'NF (rapper)',
'Nu Jerzey Devil',
'DJ Official',
'OYABUN',
'Paradime',
'Sol Patches',
'Pee-Wee (rapper)',
'J Peezy',
'Wes Period',
'Petra Bockle',
'Phats Bossi',
'Phora',
'Curtis Plum',
'The Poetess',
'Pop Da Brown Hornet',
'Popa Wu',
'Poppa LQ',
'Pouya (rapper)',
'Robin Power',
'Vidal Prevost',
'Quelle Chris',
'Radamiz',
'Dee Dee Ramone',
'Red Café',
'Boots Riley',
'RoccStar',
'Roddy Ricch',
'Brandon C. Rodegeb',
'Roqy Tyraid',
'Rubbabandz',
'Mo Sabri',
'Sagat (rapper)',
'Hasan Salaam',
'Adam Saleh',
'Sonny Sandoval',
'Savage Sun',
'Gil Scott-Heron',
'Eric Sebastian',
'Lakim Shabazz',
'Sharkula',
'Charles Shaw (singer)',
'Mac Shawn',
'Sheff G',
'Shifty Shellshock',
'Verse Simmonds',
'Sims (rapper)',
'Eric Singleton',
'Skate (rapper)',
'Sleep Dank',
'Slim Dunkin',
'Pittsburgh Slim',
'Slug Christ',
'Smartzee',
'Tim Smooth',
'SneakGuapo',
'Warren Snipe',
'Snupe',
'Soce, the elemental wizard',
'Sole (hip hop artist)',
'Solomon Ray',
'Iron Solomon',
'Spectre (musician)',
'Jesse Sprinkle',
'Stacks (rapper)',
'StaySolidRocky',
'Cousin Stizz',
'Chastain Stone',
'Moses Stone',
'Stoneface (rapper)',
'Stressmatic',
'Strick (rapper)',
'Stumik',
'Stunnaman',
'O.G. Style',
'Substantial (rapper)',
'Subtitle (rapper)',
'Suga Bang Bang',
]