export default ['Alexis & Fido',
'J Álvarez',
'Arcángel (cantante)',
'Melvin Ayala',
'Baby Rasta & Gringo',
'Tito el Bambino',
'Brytiago',
'Bad Bunny',
'Tego Calderón',
'Cosculluela',
'Darkiel',
'De La Ghetto',
'Eddie Dee',
'Deevani',
'Divino (cantante)',
'Tony Dize',
'Dyland',
'Dyland & Lenny',
'Héctor el Father',
'Ele A El Dominio',
'Anuel AA',
'Ñengo Flow',
'Farruko',
'Garay (cantante)',
'Glory (cantante)',
'Guaynaa',
'Jowell & Randy',
'Wisin',
'Kendo Kaponi',
'Lennox',
'Lito & Polaco',
'Noriel',
'Lunay',
'Magnate (cantante)',
'Bryant Myers',
'Ozuna',
'Plan B (dúo)',
'Pusho',
'Ivy Queen',
'Justin Quiles',
'Rubén DJ',
'Lenny Tavárez',
'Tempo (cantante)',
'Valentino (cantante)',
'Vico C',
'Miky Woodz',
'Yaga & Mackie',
'Yamil (cantante)',
'Yandel',
'Daddy Yankee',
'Zion (cantante)',
'Zion & Lennox',
'Alkilados',
'Pipe Calderón',
'Cali & El Dandee',
'Camilo (cantante)',
'Feid',
'J Balvin',
'Karol G',
'Legarda (cantante)',
'Maluma',
'Piso 21',
'Reykon',
'Andy Rivera',
'Kevin Roldán',
'Manuel Turizo',
'Wilson Way',
'Wolfine',
'Yandar & Yostin',
'Sebastián Yatra',
]