export default ['A.N.I.M.A.L.',
'Los Abuelos de la Nada',
'Airbag (band)',
'Alas (Argentine band)',
'Alma y Vida',
'Almendra (band)',
'Aquelarre (band)',
'Arco Iris (band)',
'Argies (band)',
'Atzmus (band)',
'Los Auténticos Decadentes',
'Babasónicos',
'Bersuit Vergarabat',
'El Bordo (band)',
'Los Brujos',
'Callejeros',
'Capitan Tifus',
'Capsula',
'La Caravana Mágica',
'Casi Justicia Social',
'Catupecu Machu',
'El Cielo (band)',
'Ciro y los Persas',
'Color Humano',
'Connor Questa',
'La cumparsita rock 72',
'Dalmanerea',
'Divididos',
'Don Cornelio y la Zona',
'Enanitos Verdes',
'Erreway',
'Los Fabulosos Cadillacs',
'Fantasmagoria',
'Las Manos de Filippi',
'Franja de Gaza',
'G.I.T.',
'Trio Galleta',
'Los Gatos (band)',
'God Save the Queen (band)',
'Los Helicópteros',
'Illya Kuryaki and the Valderramas',
'Interama',
'Karamelo Santo',
'Kumbia Queers',
'La Mosca Tsé - Tsé',
'Las Kellies',
'Lethal (Argentine band)',
'Los Beatniks',
'Los Gatos Salvajes (band)',
'Mad (band)',
'Manal',
'Massacre (Argentine band)',
'Memphis La Blusera',
'Los Natas',
'Patricio Rey y sus Redonditos de Ricota',
'Las Pelotas',
'Los Peyotes',
'Los Piojos',
'Pomada',
'PorSuiGieco',
'La Portuaria',
'Raíces (band)',
'Ratones Paranoicos',
'La Renga',
'Richter (electro rock)',
'Riff (Argentine band)',
'Robot Zonda',
'Rock Bones',
'Los Rodríguez',
'Serú Girán',
'Soda Stereo',
'Spinetta Jade',
'Suéter',
'Super Ratones',
'Tan Biónica',
'Tangocrisis',
'Tequila (band)',
'Los Tipitos',
'Todos Tus Muertos',
'La Torre (band)',
'Los Twist',
'Vilma Palma e Vampiros',
'Virus (Argentine band)',
'Viticus',
'Viuda e hijas de Roque Enroll',
'Vivencia (band)',
'Vox Dei (band)',
]