export default ['10cc',
'10 Years',
'The 1975',
'3 Doors Down',
'311',
'38 Special',
'4 Non Blondes',
'7th Order',
'? and the Mysterians',
'801',
'12 Stones',
'ABBA',
'AC/DC',
'Accept',
'Adam Ant',
'Adam Faith',
'Adam Lambert',
'Aerosmith',
'A-ha',
'Air Supply',
'Alabama',
'Albert Lee',
'Alestorm',
'Alex Chilton',
'Alan Parsons',
'Alice Cooper',
'Alice in Chains',
'Alien Ant Farm',
'All American Rejects',
'All Time Low',
'The Allman Brothers Band',
'Also Eden',
'Alter Bridge',
'Ambrosia',
'America',
'Amon Amarth',
'Anarbor',
'The Angels (American group)',
'Angels & Airwaves',
'Angel Witch',
'Angra (band)',
'The Animals',
'Anthrax',
'April Wine',
'The Archies',
'Arctic Monkeys',
'Argent',
'Art Garfunkel',
'Asia',
'Audioslave',
'Avenged Sevenfold',
'The Avett Brothers',
'Avril Lavigne',
'Awolnation',
'Ayub Bachchu',
'The B-52s',
'The Babys',
'Bachman Turner Overdrive',
'Bad Company',
'Badfinger',
'Bad Religion',
'The Band',
'Band Aid',
'The Band Perry',
'The Bangles',
'Barbara Streisand',
'Barns Courtney',
'Bastille',
'Bathory (band)',
'Bauhaus (band)',
'Bay City Rollers',
'B.B. King',
'Be-Bop Deluxe',
'Ben E. King',
'Beck',
'Beastie Boys',
'The Beatles',
'The Beach Boys',
'Bee Gees',
'Beirut',
'Ben Folds',
'Ben Folds 5',
'Better Than Ezra',
'Betty Moon',
'The Big Bopper',
'Big & Rich',
'Bill Haley & The Comets',
'Bill Withers',
'Billy Corgan',
'Billy Fury',
'Billy Idol',
'Billy J. Kramer',
'Billy Joel',
'Billy Preston',
'Billy Squier',
'Bjork',
'The Black Crowes',
'Black Flag',
'The Black Keys',
'Black Label Society',
'Black Sabbath',
'Bleachers',
'Blind Guardian',
'Blind Melon[5]',
'Blink-182',
'Blondie',
'Blood Sweat & Tears',
'Bloodhound Gang',
'Blue Öyster Cult',
'Blues Brothers',
'Blues Traveller',
'Blur',
'Bo Diddley',
'Bob Dylan[6]',
'Bob Marley',
'Bob Seger',
'Bobby Darin',
'Bobby Lewis',
'Bobby Vee',
"Booker T. and the MG's",
'Bowling For Soup',
'Bon Jovi',
'Boston',
'The Box Tops',
'Boys Like Girls',
'Boyz II Men',
'Bread',
'Breaking Benjamin',
'Brenda Lee',
'Brett Young',
'Brian Eno',
'Brian May',
'Bruce Dickinson',
'Bruce Springsteen',
'Bruce & Terry',
'Bryan Adams',
'Buck Cherry',
'Buddy Holly',
'Buffalo Springfield',
'The Buggles',
'Bush',
'Butthole Surfers',
'Buzzcocks',
'The Byrds',
'Cage the Elephant',
'Cake',
'The Calling',
'Camel (band)',
'Candlebox',
'Candlemass (band)',
'Canned Heat',
'Cannibal Corpse',
'Caravan',
'Carcass (band)',
'Carl Perkins',
'Carly Simon',
'Carole King',
'The Cars',
'The Cardigans',
'The Carpenters',
'Carrie Underwood',
'Catfish and the Bottlemen',
'Celine Dion',
'The Chantays',
'Charlie Daniels Band',
'Cheap Trick',
'Cher',
'Chevelle',
'Chicago',
'Chris Cornell',
'Chris Stapleton',
'Christopher Cross',
'Chubby Checker',
'Chuck Berry',
'Cliff Richard',
'The Clash',
'The Climax Blues Band',
'Cocteau Twins',
'Coheed and Cambria',
'Coldplay',
'Colbie Caillat',
'Collective Soul',
'Conway Twitty',
'Counting Crows',
'The Cranberries',
'The Crazy World of Arthur Brown',
'Cream',
'Creed',
'Creedence Clearwater Revival',
'Cromagnon',
'Crosby, Stills & Nash',
'Crossfade',
'The Cult',
'Culture Club',
'The Cure',
'Cypress Hill',
'Damn Yankees',
'The Damned (band)',
'Dan Fogelberg',
'Darkthrone',
'Daughtry',
'Dave Clark Five',
'David Bowie',
'David Gilmour',
'Days of the New',
'Dead Kennedys',
'Death (metal band)',
'Death Cab for Cutie',
'Deborah Harry',
'Derek and the Dominos',
'Def Leppard',
'Deep Purple',
'Depeche Mode',
'Devo',
'Dexys Midnight Runners',
'Dick Dale',
'Dickie Pride',
'Dio',
'Dire Straits',
'Disturbed',
'Dixie Chicks',
'DNCE',
'Dolly Parton',
'Don Henley',
'Donnie Iris',
'Donovan',
'The Doobie Brothers',
'Dorsey Burnette',
'Dr. Hook and the Medicine Show',
'Dream Theater',
'Drowning Pool',
'Duane Eddy',
'Duff McKagan',
'Dusty Springfield',
'The Doors',
'Duran Duran',
'E Street Band',
'Eagles',
'Eagles of Death Metal',
'Earth, Wind and Fire',
'Echo and the Bunnymen',
'Eddie Bond',
'Eddie Cochran',
'Eddie Money',
'Edgar Winter',
'Electric Light Orchestra',
'Elf (band)',
'Eloy (band)',
'Elton John',
'Elvin Bishop',
'Elvis Presley',
'Emerson Lake and Palmer',
'Emmylou Harris',
'England Dan & John Ford Coley',
'En Vogue',
'Eric Carmen',
'Eric Clapton',
'Eric Church',
'Europe',
'Eurythmics',
'Evanescence',
'Everclear',
'The Everly Brothers',
'Extreme',
'Fabian',
'Fabulous Thunderbirds',
'Faces',
'Fairport Convention',
'Faith Evans',
'Faith Hill',
'Faith No More',
'Falco',
'The Fall',
'Fall Out Boy',
'Fastball',
'Fatboy Slim',
'Fats Domino',
'Fefe Dobson',
'Fergie',
'Fifth Harmony',
'Fight (band)',
'Filter',
'Fire',
'Five For Fighting',
'Fleetwood Mac',
'Flaming Lips',
'Flock of Seagulls',
'Flogging Molly',
'Flora Cash',
'Florence and the Machine',
'Flyleaf',
'Foals',
'Focus (band)',
'Foghat',
'Foo Fighters',
'Foreigner',
'Foster the People',
'Fountains of Wayne',
'The Four Seasons',
'Frank Zappa',
'Frankie Goes to Hollywood',
'Frankie Valli',
'Franz Ferdinand',
'The Fray',
'Free',
'Freddie Mercury',
'Fuel',
'Fun',
'Funkadelic',
'Garbage',
'Gary Glitter',
'Genesis',
'Gene Vincent',
'Gene Summers',
'Gentle Giant',
'George Harrison',
'George Michael',
'George Thorogood',
'Georgia Satellites',
'Ghost B.C.',
'Gin Blossoms',
'Girls Aloud',
'Gnarls Barkley',
'Glenn Frey',
'Godsmack',
'Golden Earring',
"The Go Go's",
'Gojira (band)',
'Goo Goo Dolls',
'Good Charlotte',
'Gorillaz',
'Grand Funk Railroad',
'Grass Roots',
'Grateful Dead',
'Great White',
'Green Day',
'Gregg Allman',
'Greta Van Fleet',
'Guess Who',
"Guns N' Roses",
'Gym Class Heroes',
'Hailee Steinfeld',
'Halestorm',
'Halford (band)',
'Hall & Oates',
'Harry Chapin',
'Harry Nillson',
'Harry Styles',
'Harvey Danger',
'Hawkwind',
'Heart',
'Heaven & Hell',
'Hedley',
'Helloween',
"Herman's Hermits",
'The Hives',
'Hole',
'The Hollies',
'Hootie & The Blowfish',
'Horslips',
'House Of Pain',
'Hudson Ford',
'Huey Lewis & The News',
'Human League',
'Humble Pie',
'Iced Earth',
'Idlewild',
'Iggy Pop',
'Imagine Dragons',
'Incubus',
'INXS',
'Iona',
'Iron Butterfly',
'Iron Maiden',
'The Isley Brothers',
'Izzy Stradlin',
'J. Geils Band',
'Jack Black',
'Jack Scott',
'Jack White',
'Jackie Wilson',
'Jackson Browne',
'Jackson Five',
'Jack & Jack',
'Jake Owen',
'The Jam',
'James Taylor',
'Jan & Dean',
'Jana Kramer',
"Jane's Addiction",
'Janet Jackson',
'Janis Joplin',
'Jeff Beck',
'Jeff Beck Group',
'Jeff Buckley',
'Jefferson Airplane',
'Jefferson Starship',
'Jerry Garcia',
'Jerry Lee Lewis',
'Jethro Tull',
'The Jets',
'Jim Croce',
'Jimmy Buffett',
'Jimmy Eat World',
'Jimi Hendrix',
'The Jimi Hendrix Experience',
'Jimmy Page',
'Joan Baez',
'Joan Jett',
'Joe Cocker',
'Joe Satriani',
'Joe Walsh',
'Jon Bon Jovi',
'John Bonham',
'John Deacon',
'John Denver',
'John Densmore',
'John Entwistle',
'John Fogerty',
'John Frusciante',
'John Lennon',
'John Mayer',
'John Mayall',
'John Mayall & the Bluesbreakers',
'John Mellencamp',
'John Paul Jones',
'Johnny Burnette',
'Johnny Cash',
'Johnny Thunders',
'Johnny Winter',
'Joni Mitchell',
'Journey',
'Joy Division',
'Judas Priest',
'Julian Lennon',
'Kaiser Chiefs',
'Kaleo',
'Kansas',
'Keith Moon',
'Keith Richards',
'Kenny Loggins',
'Kenny Rogers',
'The Knack',
'Kid Rock',
'The Killers',
'Killing Joke',
'Kim Carnes',
'Kings Of Leon',
'The Kingsmen',
'The Kinks',
'Kiss',
'Korn',
'Kreator',
'Kris Kristofferson',
'King Crimson',
'L7',
'Lamb of God',
'Lana Del Rey',
'Laura Nyro',
'Lauren Daigle',
'Led Zeppelin',
'Lemmy Kilmister',
'Lenny Kravitz',
'Liam Payne',
'Lifehouse',
'Limp Bizkit',
'Linda Ronstadt',
'Lindisfarne',
'Lindsay Lohan',
'Link Wray',
'Linkin Park',
'Lita Ford',
'Little Big Town',
'Little Feat',
'Little Richard',
'Living Colour',
'Lizzy Hale',
'Loggins & Messina',
'Lonestar',
'Looking Glass',
'Loretta Lynn',
'Lou Reed',
'Louis Tomlinson',
'Loverboy',
'LRB',
"The Lovin' Spoonful",
'Lucy Hale',
'The Lumineers',
'Lush',
'Lynyrd Skynyrd',
'Mad Season',
'The Mamas and the Papas',
'Manfred Mann',
'Manic Street Preachers',
'Manowar',
'Maren Morris',
'Marian Hill',
'Marianne Faithfull',
'Maroon 5',
'The Marshall Tucker Band',
'Marty Wilde',
'The Marvellettes',
'Marillion',
'Marilyn Manson',
'Mastodon (band)',
'Matchbox Twenty',
'Meat Loaf',
'Megadeth',
'Melvins',
'Mercyme',
'Meshuggah',
'Metallica',
'Men at Work',
'MC5',
'Michael Jackson',
'Mick Jagger',
'Midnight Oil',
'Mighty Mighty Bosstones',
'Mike and the Mechanics',
'Mike Sanchez',
'Miranda Lambert',
'Misfits (band)',
'MIYAVI',
'The Monkees',
'Montgomery Gentry',
'Montrose',
'The Moody Blues',
'Jim Morrison',
'The Mothers of Invention',
'Mötley Crüe',
'Motörhead',
'Mott The Hoople',
'Mountain',
'Mudhoney',
'Mumford & Sons',
'Muse',
'My Chemical Romance',
'Nancy Sinatra',
'Natalie Cole',
'Nathaniel Rateliff',
'Nazareth',
'N.E.R.D',
'Neil Young',
'New Kids On The Block',
'New Riders of the Purple Sage',
'New Order',
'Newsboys',
'Niall Horan',
'Nick Cave and the Bad Seeds',
'Nickelback',
'Night Ranger',
'Nine Inch Nails',
'Nirvana',
'Nitty Gritty Dirt Band',
'No Doubt',
'Norah Jones',
'Norman Greenbaum',
'The Notorious B.I.G',
'Oasis',
'Of Monsters And Men',
'The Offspring',
'OneRepublic',
'Opeth',
'Orgy',
'Os Mutantes',
'The Osmonds',
'Otis Redding',
'The Outfield',
'Outlaws',
'Outkast',
'Ozark Mountain Daredevils',
'Ozzy Osbourne',
'Pantera',
'Paramore',
'Parliament',
'Parliament-Funkadelic',
'Pat Benatar',
'Patsy Cline',
'Patti Smith',
'Paul McCartney',
'Paul Revere & the Raiders',
'Paul Simon',
'Paul Weller',
'Paula Cole',
'Pearl Jam',
'Peggy Sue',
'Pete Townshend',
'Peter and Gordon',
'Peter Frampton',
'Peter Gabriel',
'Phil Collins',
'Philip Bailey',
'The Picks',
'Pink Floyd',
'Pixies',
'Plastic Ono Band',
'Poco',
'The Pogues',
'Poison',
'The Police',
'Porcupine Tree',
'Porno for Pyros',
'Portugal. The Man',
'Powerman 5000',
'Premiata Forneria Marconi',
'The Presidents of the United States of America',
'The Pretenders',
'The Pretty Things',
'Primal Scream',
'The Proclaimers',
'The Prodigy',
'Primus (band)',
'Prince',
'Procol Harum',
'Puddle of Mudd',
'Pure Prairie League',
'Q5',
'Queen',
'Queens of the Stone Age',
'Queensrÿche',
'The Quarrymen',
'Quiet Riot',
'The Raconteurs',
'Radiohead',
'Rage Against the Machine',
"Rag'n'Bone Man",
'Rainbow',
'Ram Jam',
'Ramones',
'Rammstein',
'Randy Rhoads',
'The Rascals',
'Rascal Flatts',
'The Rasmus',
'The Raspberries',
'Ratt',
'Ray Charles',
'Redbone',
'Red Hot Chili Peppers',
'Red Rider',
'R.E.M.[20]',
'REO Speedwagon',
'The Replacements',
'Rhapsody of Fire',
'Richard Hell',
'Rick James',
'Ricky Nelson',
'Ringo Starr',
"Ringo Starr's All-Starr Band",
'Rise Against',
'Ritchie Valens',
'Rob Halford',
'Rob Thomas',
'Rob Zombie',
'Robbie Williams',
'Robert Palmer',
'Robert Plant',
'Rod Stewart',
'Roger Daltrey',
'Roger Taylor',
'Roger Waters',
'The Rolling Stones',
'The Ronettes',
'Ronnie James Dio',
'Ronny & the Daytonas',
'Rory Storm',
'Roxette',
'Roxy Music',
'Roy Orbison',
'Run-D.M.C.',
'Rush',
'Samantha Fox',
'Sammy Hagar',
'Santana',
'Sara Bareilles',
'Savage Garden',
'Scafell Pike',
'Scream',
"Screamin' Jay Hawkins",
'Screaming Trees',
'The Script',
'Scorpions',
'Seals & Croft',
'Sean Kingston',
'Sean Lennon',
'Semisonic',
'Sepultura',
'Sex Pistols',
'Shaed',
'Shakin Stevens',
'Shania Twain',
'The Shirelles',
'Shinedown',
'Slash',
'Silver Bullet Band',
'Silversun Pickups',
'Simon & Garfunkel',
'Simple Plan',
'Siouxsie and the Banshees',
'Sir Mix-a-Lot',
'Sir Sly',
'The Sisters of Mercy',
'Skid Row',
'Skillet',
'Skrillex',
'Slade',
'Slayer',
'Slipknot',
'Sleater-Kinney',
'Sly & The Family Stone',
'Smash Mouth',
'The Smashing Pumpkins',
'The Smiths',
'Smokey Robinson',
'Smokie',
'Social Distortion',
'Sonata Arctica',
'Sonic Youth',
'Sonny Bono',
'Sonny & Cher',
'Soundgarden',
'Spandau Ballet',
'The Specials',
'Spencer Davis Group',
'Sponge',
'Squeeze',
'Staind',
'Starship',
'Status Quo',
'Steeleye Span',
'Steely Dan',
'Steppenwolf',
'Steve Miller Band',
'Steve Winwood',
'Steven Adler',
'Stevie Ray Vaughan',
'Sting',
'Stone Temple Pilots',
'Stone the Crows',
'Stone Sour',
'The Stooges',
'Strawbs',
'Stray Cats',
'The Strokes',
'Styx',
'Sublime',
'Sublime With Rome',
'Sugarhill Gang',
'Sugarland',
'Sugar Ray',
'Sum 41',
'Sunny Day Real Estate',
'Supercar',
'Supertramp',
'The Supremes',
'The Surfaris',
'Survivor (band)',
'Sweet',
'Switchfoot',
'Syd Barrett',
'System Of A Down',
'T. Rex',
'Take That',
'Talking Heads',
'Talk Talk',
'Tangerine Dream',
'Tantric',
'Tears for Fears',
'Ted Nugent[25]',
'Tempest (Celtic rock band)',
'Tempest (Christian rock band)',
'Tempest (musician)',
'Tempest (UK band)',
'The Tempests (band)',
'Temple of the Dog',
'Temptations',
'Ten Years After',
'Tenacious D',
'Terry Knight and the Pack',
'Tesla',
'Testament (band)',
'Them',
'Them Crooked Vultures',
'Theory of a Deadman',
'Thompson Twins',
'Three Dog Night',
'Three Days Grace',
'Thin Lizzy',
'Third Eye Blind',
'Thirty Seconds to Mars',
'Tina Turner',
'Toadies',
'Toby Keith',
'Tokio Hotel',
'Tom Cochrane',
'Tom Petty',
'Tom Petty and the Heartbreakers',
'Tom Robinson Band[26]',
'Tommy & The Tom Toms',
'Tommy James & the Shondells',
'Tonic',
'Tool (band)',
'Tori Kelly',
'Toto',
'Tommy Tutone',
'Tove Lo',
'Trace Adkins',
'Traffic',
'Train',
'Traveling Wilburys',
'Travis',
'Travis Tritt',
'Travie McCoy',
'Trivium',
'Troggs',
'Tupac',
'The Turtles',
'Type O Negative',
'Twisted Sister',
'U2',
'UB40',
'Uncle Kracker',
'Uriah Heep',
'Vampire Weekend',
'Van Halen',
'Van Morrison',
'Van Zant',
'VAST',
'Velvet Revolver',
'The Velvet Underground',
'Vertical Horizon',
'The Verve',
'The Verve Pipe',
'Village People',
'Vince Taylor',
'Volbeat',
'Wallows',
'Wanda Jackson',
'War',
'Warren Smith',
'Warren Zevon',
'Waylon Jennings',
'We the Kings',
'Weezer',
'Weird Al Yankovic',
'Whitesnake',
'The White Stripes',
'White Zombie',
'The Who',
'Wilbert Harrison',
'Willie Nelson',
'Winger',
'Wings',
'Wolfmother',
'X',
'XTC',
'X Ambassadors',
'The Yardbirds',
'Yes',
'Young the Giant',
'The Youngbloods',
'Zac Brown Band',
'Zakk Wylde',
'Zebra (American band)',
'Zebra (Yugoslav band)',
'The Zombies',
'ZZ Top',
]