export default ['Omar Alfanno',
'Melina Almodóvar',
'Anaé',
'Marc Anthony',
'Pedro Arroyo',
'Miguel Ángel Barcasnegras',
'Basilio (cantante)',
'Rubén Blades',
'Amilcar Boscan',
'Ángel Canales',
'Charlie Cruz',
'Mariano Cívico',
'Willie Colón',
'Elvis Crespo',
'Bobby Cruz',
"Oscar D'León",
'Luis de los Reyes',
'Diamela del Pozo',
'Huey Dunbar',
'Cano Estremera',
'Cheo Feliciano',
'Ruth Fernández',
'Henry Fiol',
'Gaitanes',
'Tito Gómez (cantante)',
'Willie González',
'Paquito Guzmán',
'José Alberto "El Canario"',
'La India (cantante)',
'Héctor Lavoe',
'Lucrecia (cantante)',
'Luis Enrique (cantante)',
'Cheo Marquetti',
'Alex Matos (cantante)',
'Canelita Medina',
'Melcochita',
'Ismael Miranda',
'Monguito',
'Andy Montañez',
'Tito Nieves',
'Oscarcito',
'Chichí Peralta',
'Nelson Pinedo',
'Víctor Piñero',
'Florentino Primera',
'Servando Primera',
'Carlos "Tabaco" Quintana',
'Ismael Quintana',
'Domingo Quiñones',
'Richie Ray',
'Edwin Rivera',
'Ismael Rivera',
'Jerry Rivera',
'Johnny Rivera',
'Roberto Antonio',
'Roberto Blades',
'Pellín Rodríguez',
'Pete "El Conde" Rodríguez',
'Tito Rodríguez',
'Tito Rojas',
'Frankie Ruiz',
'Viti Ruiz',
'Rey Ruiz',
'Rolf Sanchez',
'Saned',
'Gilberto Santa Rosa',
'Santiago Cerón',
'Adalberto Santiago',
'Eddie Santiago',
'Raúl Serrano',
'Michael Stuart',
'Olga Tañón',
'Mickey Taveras',
'Héctor Tricoche',
'Tony Vega',
'Julio Voltio',
'Víctor Waill',
]