export default [
        'Pop',
        'Rap',
        'Hip hop',
        'Trap',
        'Reggaeton',
        'Kpop',
        'Jpop',
        'Country',
        'Rock',
        'Salsa',
        'Metal',
        'Cumbia',
        'Punk',
        'Baladas',
        'Jazz',
        'Electrónica',
        'R&B',
        'Rock nacional',
]